apiVersion: v1beta3
kind: Pod
metadata:
  name: music-db
  namespace: mytunes
  labels:
    name: music-db
spec:
  containers:
  - name: es
    image: kubernetes/elasticsearch:1.0
    env:
      - name: "CLUSTER_NAME"
        value: "music-db"
      - name: "SELECTOR"
        value: "name=music-db"
      - name: "NAMESPACE"
        value: "mytunes"
    ports:
    - name: es
      containerPort: 9200
    - name: es-transport
      containerPort: 9300
    volumeMounts:
    - name: apiserver-secret
      mountPath: /etc/apiserver-secret
      readOnly: true
  volumes:
  - name: apiserver-secret
    secret:
      secretName: apiserver-secret
