apiVersion: v1beta3
kind: Pod
metadata:
  name: fluentd-elasticsearch
spec:
  containers:
  - name: fluentd-elasticsearch
    image: gcr.io/google_containers/fluentd-elasticsearch:1.6
    env:
    - name: "FLUENTD_ARGS"
      value: "-vv"
    volumeMounts:
    - name: varlog
      mountPath: /varlog
    - name: containers
      mountPath: /var/lib/docker/containers
    - name: token-system-logging
      mountPath: /etc/token-system-logging
      readOnly: true
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
  - name: token-system-logging
    secret:
      secretName: token-system-logging
